### ISSUE TITLE
why is does not work?

### ISSUE THREAD

**Issue by qwejinxiaozhe** [FrankTheBoxMonster/LoL-SCB-fixer#1]
Hello, after I use this tool to convert. SCB files, why can't I open it in Maya 2013? Is my RiotFileTranslator plug-in version too old?

**Comment by FrankTheBoxMonster** [comment]
It's meant to work with Maya 2015 and the version of the plugin that I have attached here.

If you send me which file you are trying to convert I can see if it's an issue with that file or if you're just using the wrong plugin version.

https://cdn.discordapp.com/attachments/449907181148438528/510903056897146911/riotfiletranslator_plugin_copy.zip

**Comment by qwejinxiaozhe** [comment]
Unbelievable. Successful.I confirm that the MAYA 2013 version is too old.I read. SCB in Maya 2017 and succeeded, amazing tool. Thank you for your help.
